# Generated by Django 2.1.5 on 2023-05-20 21:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('lieu', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=2083)),
                ('organisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.Organisateur')),
            ],
        ),
    ]
