# Generated by Django 2.1.5 on 2023-05-21 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0002_auto_20230520_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='team_1',
            field=models.CharField(default='Hassania Agadir', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='team_2',
            field=models.CharField(default='Association Sale', max_length=255),
            preserve_default=False,
        ),
    ]
