# Generated by Django 2.1.5 on 2023-05-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0003_auto_20230521_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='image_url',
        ),
        migrations.AddField(
            model_name='events',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
