# Generated by Django 2.1.5 on 2023-05-28 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0004_auto_20230528_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='team_1',
        ),
        migrations.RemoveField(
            model_name='events',
            name='team_2',
        ),
    ]
