# Generated by Django 4.2.2 on 2023-06-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0005_auto_20230528_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to='images'),
        ),
    ]
