# Generated by Django 5.1.4 on 2024-12-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0007_alter_events_organisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
