# Generated by Django 2.1.5 on 2023-05-27 19:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users_app', '0005_auto_20230521_0310'),
        ('events_app', '0003_auto_20230521_0219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.Client')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events_app.Events')),
            ],
        ),
    ]
