# Generated by Django 2.1.5 on 2023-06-06 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='event',
            new_name='match',
        ),
    ]
