# Generated by Django 4.2.2 on 2023-06-11 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_app', '0002_auto_20230606_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='status',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Reserve', 'Reserve')], default='Disponible', max_length=10),
        ),
        migrations.AddField(
            model_name='tickets',
            name='ticket_type',
            field=models.CharField(choices=[('Regulier', 'Regulier'), ('VIP', 'VIP')], default='Regulier', max_length=10),
        ),
    ]
