# Generated by Django 4.2.2 on 2023-06-11 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_app', '0003_tickets_status_tickets_ticket_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='nbr',
            field=models.IntegerField(default=1),
        ),
    ]
