# Generated by Django 4.2.2 on 2023-06-21 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_app', '0004_tickets_nbr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='status',
        ),
    ]
