# Generated by Django 2.1.5 on 2023-05-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisateur',
            name='categorie',
            field=models.CharField(choices=[('CAF', 'CAF'), ('BOTOLAPRO', 'Botola PRO'), ('CoupeTrone ', 'Coupe du Trone ')], max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_type',
            field=models.CharField(choices=[('Client', 'Client'), ('Organisateur', 'Organisateur'), ('Admin', 'Admin')], max_length=255),
        ),
    ]
