# Generated by Django 2.1.5 on 2023-05-21 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_auto_20230521_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisateur',
            name='categorie',
            field=models.CharField(choices=[('BOTOLAPRO', 'Botola PRO'), ('BOTOLA2', 'Botola 2'), ('CoupeTrone ', 'Coupe du Trone'), ('AmateurLeague ', 'Amateur League')], max_length=255),
        ),
    ]
