# Generated by Django 2.1.5 on 2023-05-21 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_auto_20230521_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisateur',
            name='categorie',
            field=models.CharField(choices=[('Botola PRO', 'Botola PRO'), ('Botola 2', 'Botola 2'), ('Coupe du Trone', 'Coupe du Trone'), ('Amateur League', 'Amateur League')], max_length=255),
        ),
    ]
