# Generated by Django 4.2.2 on 2023-06-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0006_remove_users_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profile_img',
            field=models.ImageField(blank=True, default='profile_img_default.png', upload_to=''),
        ),
    ]
