# Generated by Django 4.2.2 on 2023-06-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0007_users_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisateur',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
