# Generated by Django 5.1.4 on 2024-12-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0008_alter_organisateur_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisateur',
            name='categorie',
            field=models.CharField(choices=[('LaLiga', 'LaLiga'), ('Serie A', 'Serie A'), ('Coupe du Monde', 'Coupe du Monde'), ('Champions League', 'Champions League')], max_length=255),
        ),
    ]
